version: "3.8"
services:

  #Nginx Service
  nginx:
    image: nginx:stable
    volumes:
      - ./src:/src
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
    ports:
      - 80:80
    networks:
      app-network:
        aliases:
          - nginx
    depends_on:
      - php

  #PHP Service
  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/src
    working_dir: /src
    networks:
      app-network:
        aliases:
          - php
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lumendb
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      app-network:
        aliases:
          - mysql

  #PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PHP_UPLOAD_MAX_FILESIZE: 100MB
    networks:
      app-network:
        aliases:
          - phpmyadmin

#Docker Networks
networks:
  app-network:
